DELETE FROM documents;
DELETE FROM spendings;
DELETE FROM user_notifications;
DELETE FROM senders;
DELETE FROM tags;
DELETE FROM groups;
DELETE FROM users WHERE id>1;

ALTER TABLE users AUTO_INCREMENT = 1000;
ALTER TABLE documents AUTO_INCREMENT = 1000;
ALTER TABLE spendings AUTO_INCREMENT = 1000;
ALTER TABLE groups AUTO_INCREMENT = 1000;
ALTER TABLE tags AUTO_INCREMENT = 1000;
ALTER TABLE roles AUTO_INCREMENT = 1000;
ALTER TABLE rights AUTO_INCREMENT = 1000;
ALTER TABLE user_notifications AUTO_INCREMENT = 1000;
ALTER TABLE senders AUTO_INCREMENT = 1000;
ALTER TABLE document_history AUTO_INCREMENT = 1000;
ALTER TABLE documents_rights AUTO_INCREMENT = 1000;
ALTER TABLE users_document_requests AUTO_INCREMENT = 1000;

UPDATE users SET email='superadmin@comune1.fr.it' WHERE id = 1;
